#In this makefile we are accepting the input from user as a command line
#which gets stored in macro ARGS

build:
	gcc cpCmdImpl.c -o cp
run:
	./cp ${ARGS}
usage:
	@echo 'use as : make ARGS="CommandLine_Argument" run'

	
	
